# Damn Vulnerable NodeJS Application

version: "2.1"
services:
  app:
    networks:
      - net
    build:
      context: ./
      dockerfile: Dockerfile-dev
    ports:
      - 9090:9090
    volumes:
      - .:/app
    depends_on:
      - mysql-db
    env_file:
      - ./vars.env

  mysql-db:
    networks:
      - net
    image: mysql:latest
    expose:
      - "3306"
    env_file:
      - ./vars.env

networks:
  net:
    driver: bridge